"""Synthetic demonstration datasets.

These let a first-time visitor run the whole workflow without having to
upload anything. The fields are deliberately generic: a smooth spatial
pattern with a seasonal cycle and noise, not any particular geophysical
product. The candidate is derived from the reference with a known bias and
scaling, so the resulting metrics are predictable and easy to explain.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import xarray as xr

from .config import APP_NAME


def make_demo_pair(
    days: int = 180,
    lat_range: tuple[float, float] = (8.0, 34.0),
    lon_range: tuple[float, float] = (68.0, 96.0),
    resolution: float = 1.0,
    seed: int = 20240101,
) -> tuple[xr.Dataset, xr.Dataset]:
    """Build a matched (candidate, reference) pair of daily gridded datasets.

    The candidate carries a +12% scaling and a small positive offset relative
    to the reference, plus independent noise, so correlation is high while
    PBIAS and Bias are clearly non-zero.
    """
    rng = np.random.default_rng(seed)

    time = pd.date_range("2020-01-01", periods=days, freq="D")
    lat = np.arange(lat_range[0], lat_range[1] + resolution / 2, resolution)
    lon = np.arange(lon_range[0], lon_range[1] + resolution / 2, resolution)

    day_of_year = time.dayofyear.to_numpy(dtype="float64")
    seasonal = 1.0 + 0.8 * np.sin(2 * np.pi * (day_of_year - 80) / 365.25)

    # Day-to-day variability shared by both datasets. Without it the only
    # temporal signal is the slow seasonal cycle, which barely moves across a
    # short window and would leave correlation dominated by noise.
    weather = rng.normal(0.0, 1.0, days)
    weather = np.convolve(weather, np.array([0.25, 0.5, 0.25]), mode="same")
    temporal = np.clip(seasonal + 0.7 * weather, 0.05, None)

    lat_grid, lon_grid = np.meshgrid(lat, lon, indexing="ij")
    spatial = (
        2.5
        + 1.5 * np.cos(np.deg2rad(lat_grid - 20) * 3.0)
        + 0.8 * np.sin(np.deg2rad(lon_grid - 78) * 2.0)
    )
    spatial = np.clip(spatial, 0.2, None)

    base = temporal[:, None, None] * spatial[None, :, :]

    reference_values = np.clip(base + rng.normal(0.0, 0.25, base.shape), 0.0, None)
    candidate_values = np.clip(
        base * 1.12 + 0.15 + rng.normal(0.0, 0.35, base.shape), 0.0, None
    )

    # A ragged corner of missing data, so the demo also exercises NaN handling.
    candidate_values[:, :2, :2] = np.nan

    def build(values: np.ndarray, label: str, description: str) -> xr.Dataset:
        dataset = xr.Dataset(
            {
                "value": (
                    ("time", "lat", "lon"),
                    values.astype("float32"),
                    {
                        "long_name": f"Synthetic gridded value ({label})",
                        "units": "unitless",
                    },
                )
            },
            coords={
                "time": time,
                "lat": ("lat", lat, {"units": "degrees_north", "standard_name": "latitude"}),
                "lon": ("lon", lon, {"units": "degrees_east", "standard_name": "longitude"}),
            },
            attrs={
                "title": f"{APP_NAME} demonstration dataset ({label})",
                "summary": description,
                "source": f"Generated by {APP_NAME} for demonstration purposes only",
                "Conventions": "CF-1.8",
            },
        )
        return dataset

    candidate = build(
        candidate_values,
        "candidate",
        "Synthetic candidate: the reference pattern with a +12% scaling, a +0.15 offset, "
        "independent noise, and a block of missing values.",
    )
    reference = build(
        reference_values,
        "reference",
        "Synthetic reference: a smooth spatial pattern with a seasonal cycle and light noise.",
    )
    return candidate, reference


def demo_bytes(dataset: xr.Dataset) -> bytes:
    """Serialise a demo dataset to NetCDF bytes for the download buttons."""
    return bytes(dataset.to_netcdf())
